import Head from "next/head";
import styles from "../styles/Home.module.css";
import DevGroves from "./src";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DevGroves />

      <footer className={styles.footer}>
        Powered by <span> DevGroves</span>
      </footer>
    </div>
  );
}
